### PR TITLE
Styled Nav and added Footer

### PR DESCRIPTION
**Pull request by ericyuart**
Styled the navigation bar and the footer, using font awesome and Muli.  Also beware of the signup form, there might be some styling issues.

### CODE REVIEW

**Comment by ksegal** [comment]
@ericyuart: Did we figure out what was wrong with this?

**Comment by nbokil** [comment]
@ksegal He put the <% yield %> inside the logged_in tag, so you can't view anything unless ur logged in. I think @ericyuart fixed it locally, can u push ur latest code?

**Comment by ericyuart** [comment]
Added the commit where I put the yield in the proper place.

**Comment by ksegal** [comment]
logging out is correct now, however the footer still appears in weird places.

**Pull request merged**
